function handheldGPSpoints = importGPShandheld(filename)
%IMPORTFILE Import data from a text file
%  DELMAR17GCPS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DELMAR17GCPS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  DelMar17GCPs = importfile("C:\Users\Carson\Documents\Git\SIOCameraRectification\data\20250614\20250614_DelMar17_GCPs.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Aug-2025 16:28:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Name", "Latitude", "Longitude", "H", "Code", "Northings", "Eastings", "Elevation", "HSDV", "VSDV", "STATUS", "SATS", "AGE", "PDOP", "HDOP", "VDOP", "TDOP", "GDOP", "NSDV", "ESDV", "DATE", "TIME", "RODHGT"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Code", "DATE", "TIME", "RODHGT"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Code", "STATUS", "DATE", "TIME", "RODHGT"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["HSDV", "VSDV", "SATS", "AGE", "PDOP", "HDOP", "VDOP", "TDOP", "GDOP", "NSDV", "ESDV"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["HSDV", "VSDV", "SATS", "AGE", "PDOP", "HDOP", "VDOP", "TDOP", "GDOP", "NSDV", "ESDV"], "ThousandsSeparator", ",");

% Import the data
handheldGPSpoints = readtable(filename, opts);

tableshape=size(handheldGPSpoints);

for i=1:tableshape(1)
    if(handheldGPSpoints.DATE{i}(1:5)=='DATE:')
        handheldGPSpoints.DATE{i}(1:5)=[];
    end
    if(handheldGPSpoints.TIME{i}(1:5)=='TIME:')
        handheldGPSpoints.TIME{i}(1:5)=[];
    end
end

end